name: grid_animation
description: Grid view Gridview_Animation is like dealing cards. 
version: 0.0.3
homepage: https://github.com/lovekid1997/grid_view_animation
repository: https://github.com/lovekid1997/grid_view_animation
issue_tracker: https://github.com/lovekid1997/grid_view_animation/issues
documentation: https://github.com/lovekid1997/grid_view_animation/blob/main/README.md

environment:
  sdk: '>=2.18.4 <3.0.0'
  flutter: ">=1.17.0"

dependencies:
  collection: ^1.16.0
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
